name: tools-sync

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push: 
      branches: [fix-tools-sync]

jobs:
  sync-tools-docs: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Pull tools docs
      run: npm run docs:tools:sync

    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    - name: Create Pull Request
      if: steps.changes.outputs.changed == 1
      uses: peter-evans/create-pull-request@v3
      with: 
        draft: false
        branch: tools-docs-sync
        delete-branch: true
        title: Update Tools Documentation
        body: Update changes from ERC725.js and LSP-Factory repositories 
